---
AllCops:
  DisplayCopNames:    true
  DisplayStyleGuide:  true
  StyleGuideCopsOnly: true
  TargetRubyVersion:  2.3

Style/Alias:
  Enabled: false

Style/FileName:
  Exclude:
    - lib/evil-client.rb

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Exclude:
    - spec/**.rb

Style/NumericPredicate:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Exclude:
    - spec/**.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolProc:
  Exclude:
    - spec/**.rb
