---
AllCops:
  DisplayCopNames:    true
  DisplayStyleGuide:  true
  StyleGuideCopsOnly: true
  TargetRubyVersion:  2.3

Style/Alias:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SingleLineMethods:
  Exclude:
    - spec/**/*_spec.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
