---
sudo:     false
language: ruby
cache:    bundler
before_install: gem install bundler -v 1.12.5
script:   bundle  exec rspec
rvm:
  - '2.2'
  - '2.3.0'
  - rbx-2
  - ruby-head
  - jruby-9
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
